# Generated by Django 4.1.3 on 2022-11-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(max_length=150, verbose_name='ФИО')),
                ('Birthday', models.CharField(max_length=10, verbose_name='День рождения')),
                ('Froms', models.CharField(max_length=60, verbose_name='Гражданство')),
                ('Pasport', models.CharField(max_length=20, verbose_name='Серия и номер паспорта')),
                ('Data_pasport', models.CharField(max_length=10, verbose_name='Дата выдачи')),
                ('Number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('status', models.CharField(max_length=1, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
