# Generated by Django 4.1.3 on 2022-11-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='INFO',
            field=models.TextField(default=1, max_length=20, verbose_name='Серия и номер паспорта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='Birthday',
            field=models.DateField(max_length=10, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='form',
            name='Data_pasport',
            field=models.DateField(max_length=10, verbose_name='Дата выдачи'),
        ),
    ]
