# Generated by Django 4.1.3 on 2022-11-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_form_info_alter_form_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='nikname',
            field=models.CharField(default=1, max_length=150, verbose_name='nikname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='INFO',
            field=models.TextField(max_length=20, verbose_name='Сведения о недвижемости'),
        ),
    ]
