# Generated by Django 4.1.3 on 2022-11-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_form_razdel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikname', models.CharField(max_length=150, verbose_name='nikname')),
                ('razdel', models.CharField(max_length=150, verbose_name='Раздел')),
                ('USER_NAME', models.CharField(max_length=150, verbose_name='ФИО')),
                ('Birthday', models.DateField(max_length=10, verbose_name='День рождения')),
                ('Froms', models.CharField(max_length=60, verbose_name='Гражданство')),
                ('Pasport', models.CharField(max_length=20, verbose_name='Серия и номер паспорта')),
                ('INFO', models.TextField(max_length=120, verbose_name='Сведения о недвижемости')),
                ('Data_pasport', models.DateField(max_length=10, verbose_name='Дата выдачи')),
                ('Number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('status', models.CharField(max_length=1, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Form3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikname', models.CharField(max_length=150, verbose_name='nikname')),
                ('razdel', models.CharField(max_length=150, verbose_name='Раздел')),
                ('USER_NAME', models.CharField(max_length=150, verbose_name='ФИО')),
                ('Birthday', models.DateField(max_length=10, verbose_name='День рождения')),
                ('Froms', models.CharField(max_length=60, verbose_name='Гражданство')),
                ('Pasport', models.CharField(max_length=20, verbose_name='Серия и номер паспорта')),
                ('INFO', models.CharField(max_length=40, verbose_name='Сведения о недвижемость')),
                ('Data_pasport', models.DateField(max_length=10, verbose_name='Дата выдачи')),
                ('Number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('status', models.CharField(max_length=1, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Form4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikname', models.CharField(max_length=150, verbose_name='nikname')),
                ('razdel', models.CharField(max_length=150, verbose_name='Раздел')),
                ('USER_NAME', models.CharField(max_length=150, verbose_name='ФИО')),
                ('Birthday', models.DateField(max_length=10, verbose_name='День рождения')),
                ('Froms', models.CharField(max_length=60, verbose_name='Гражданство')),
                ('Pasport', models.CharField(max_length=20, verbose_name='Серия и номер паспорта')),
                ('INFO', models.CharField(max_length=40, verbose_name='Недвижемость')),
                ('Data_pasport', models.DateField(max_length=10, verbose_name='Дата выдачи')),
                ('Number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('status', models.CharField(max_length=1, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Form5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikname', models.CharField(max_length=150, verbose_name='nikname')),
                ('razdel', models.CharField(max_length=150, verbose_name='Раздел')),
                ('USER_NAME', models.CharField(max_length=150, verbose_name='ФИО')),
                ('Birthday', models.DateField(max_length=10, verbose_name='День рождения')),
                ('Froms', models.CharField(max_length=60, verbose_name='Гражданство')),
                ('Number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('status', models.CharField(max_length=1, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Form6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikname', models.CharField(max_length=150, verbose_name='nikname')),
                ('razdel', models.CharField(max_length=150, verbose_name='Раздел')),
                ('USER_NAME', models.CharField(max_length=150, verbose_name='ФИО')),
                ('Birthday', models.DateField(max_length=10, verbose_name='День рождения')),
                ('Number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('status', models.CharField(max_length=1, verbose_name='Статус')),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='INFO',
            field=models.TextField(max_length=120, verbose_name='Сведения о недвижемости'),
        ),
    ]
