# Generated by Django 4.1.3 on 2022-11-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_form2_form3_form4_form5_form6_alter_form_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='geeks_field',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
