# Generated by Django 4.1.3 on 2022-11-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_form_geeks_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='geeks_field',
        ),
    ]
